### ISSUE TITLE
Add support for WebDAV

### ISSUE THREAD

**Issue by prabirshrestha** [lithium0003/ccViewer#1]
Would it be possible to have WebDAV support? Currently rclone allows us to serve any remote as WebDAV server which means we can start interacting with backends currently not supported by ccViewer.

**Comment by lithium0003** [comment]
It sounds good. I'll plan to implement WebDAV backend.

**Comment by Jwink3101** [comment]
This would be very useful since, as it stands now, the backends themselves are not self-hosted. Any self hosted backend would be appreciated (webDAV, FTP, SFTP, etc)
