### ISSUE TITLE
Allow to cancel current download

### ISSUE THREAD

**Issue by prabirshrestha** [lithium0003/ccViewer#13]
I noticed that when the image or file is downloading there is no way to cancel the download so I have to wait before I can start another task. This starts to become problematic for large files or when the internet connection is slow.

**Comment by lithium0003** [comment]
Download progress indicator and cancel button is now testing. It will be implemented in next release.
In store version, back navigation breaks downloading.

**Comment by prabirshrestha** [comment]
Files app seems to implement it in a good way.

When we click the image it shows a new screen with done button and loading indicator. If I click done before it has downloaded it cancels the download. This also allows to have custom buttons like sharing or delete in the future. Clicking the image then takes it to full screen.

**Comment by lithium0003** [comment]
This  feature is implemented in internal beta version.
