### ISSUE TITLE
Audio stream only plays background sounds, not main voices

### ISSUE THREAD

**Issue by redronin** [lithium0003/ccViewer#15]
I’ve been playing a few of my media files and it seems videos that have 5.1 sound, only the music and background sounds are being played, not the main voices.

I think it only happens w media files that have 5.1 or more channels?

These were files streaming from A google drive share.

Changing the sound stream has no effect

**Comment by lithium0003** [comment]
It may be failed to down mix to stereo, I'll check it.

**Comment by lithium0003** [comment]
Rewrite player module and change the down mix way in v1.4.0

**Comment by lithium0003** [comment]
How about errors in version 1.4.1?

**Comment by redronin** [comment]
I tried a few streams w/ 5.1 sound and main voices could be heard. 👍
