### ISSUE TITLE
Not all files from encrypted rclone drive are shown

### ISSUE THREAD

**Issue by redronin** [lithium0003/ccViewer#16]
I have a google drive share which I upload files via encrypted rclone from my desktop machine.

Using the crypt rclone folder, most files and directories are properly decrypted, but a few files do not show up, even though they exist in encrypted form.

So, some files are not being unencrypted properly, and therefore the directory looks like there are no files there. This happens with a number of directories, not just a single incident.

Attached is screenshot of the encrypted files, and then the unencrypted directory.
![30175EB9-149E-4F27-9BB0-FE9FB71082CE](https://user-images.githubusercontent.com/10535/68785773-8680c800-05f3-11ea-8838-b8e5eb1e48c3.png)
![84BA4781-4ADD-411F-9825-ABA664172767](https://user-images.githubusercontent.com/10535/68785775-8680c800-05f3-11ea-9bc7-eec8323a14f9.png)

**Comment by lithium0003** [comment]
Can the files failed to decrypt decrypt with rclone correctly? This happened when decrypt engine failed to decrypt names. It will occur when password/salt pair is incorrect.
`rclone ls crypt:` works correctly?

**Comment by redronin** [comment]
I’m away on vacation right now and don’t have access to Rclone on my box at home. Will report back when I get home.

Most directories have files in them but some are missing - but actually it could be the ones I think are decrypted to proper name might not be the same folder. So I will check when I get home and report back.

**Comment by lithium0003** [comment]
#17 related bug
check the round up logic

**Comment by redronin** [comment]
Not a bug. Seems like I had a number of empty folders which I didn't realize.
