### ISSUE TITLE
Crash in Settings view 

### ISSUE THREAD

**Issue by kfur** [lithium0003/ccViewer#20]
Strange crash with `[UIFont monospacedSystemFontOfSize:weight:]: unrecognized selector sent to class` exception occurred every time in settings.
[CryptCloudViewer-2019-11-18-125130.txt](https://github.com/lithium0003/ccViewer/files/3858840/CryptCloudViewer-2019-11-18-125130.txt)

**Comment by lithium0003** [comment]
In iOS 12, that function is documented available but actually is not supported. Fix it next version.
