### ISSUE TITLE
App crashes when rclone encryption password has an ñ on it

### ISSUE THREAD

**Issue by JulKeZ** [lithium0003/ccViewer#24]
I tried to add a remote with encryption. My second password contained an ñ, which is a common character in Spain. After submitting, the app crashes, and I am unable to use the name of the remote again, since the app crashes again. I changed the password and used an n instead of an ñ, and everything works fine now. I have another problem with iOS, since I am unable to delete the ccViewer app config just to use the name of the remote I want. If iOS doesn't delete the config, there should be an option on the app just to restart from scratch...
Thankyou for your great work!

**Comment by lithium0003** [comment]
Thanks for reporting and sorry for inconvenience. In my implementation, the second password only accept ascii characters now. It should be fixed soon.
All secure configuration, such as passwords or tokens, are kept in iOS keychains so not removed by app reinstall. In developing version, add remove option and kept in iCloud keychains so multi-devices synchronization is allowed.
