### ISSUE TITLE
Crashes when the cache limit is reached

### ISSUE THREAD

**Issue by RickyBubbles** [lithium0003/ccViewer#25]
App seems to crash when the cache limit is reached (e.g. if I open two files, the first one fits wholly in the cache, the second file will exceed the cache size, and the app will crash).  Opening the app after crashing usually shows that "Cache Size" has come to exceed "Cache Limit"

...also, is there a "purge cache" option?  I've just been setting the limit to zero and restarting the app to accomplish this, but I'm not sure that it actually purges the files.

**Comment by lithium0003** [comment]
Thanks for reporting bug. I'll check it and fix next release.
