### ISSUE TITLE
Can you add ability to upload ?

### ISSUE THREAD

**Issue by bingoxo** [lithium0003/ccViewer#41]
I know the app is called viewer , but it has the potential to be a very good FOSS cloud drive mmanagement tool :)

**Comment by lithium0003** [comment]
In 'Edit items' menu, single file upload is implemented.

![A6C85600-3573-47EE-BE4A-8531634A4CB4_1_105_c](https://user-images.githubusercontent.com/4783887/115438693-aa185b00-a248-11eb-9f9c-a0f7855753ad.jpeg)
![A21A71C6-A03A-4E0F-B5FB-E944D53385C2_1_105_c](https://user-images.githubusercontent.com/4783887/115438700-abe21e80-a248-11eb-851e-93e43d002094.jpeg)
