### ISSUE TITLE
Add support for better image viewer

### ISSUE THREAD

**Issue by prabirshrestha** [lithium0003/ccViewer#7]
Currently it is very difficult to exit the image preview due to no close button. Nikon RAW files also seems to crash the app.

Would be good to also use left right movements to go to next file or image.

**Comment by lithium0003** [comment]
1) To close the window, left edge swipe is assigned now. In iOS13, it seems down swipe is common close gesture. Is the close button easier to access than gesture?
2) If you have any Nikon RAW file, please share a file to crash. I don't have any RAW files.
3) It sounds good that Right/Left swipe gesture for previous/next image to easy exploring folder. It will be implemented next version.

**Comment by prabirshrestha** [comment]
Currently the left swap is not reliable and I need to try it multiple times so anything would be better. +1 for down swipe and left right for next and previous. I’m ok for not having close button yet if it works reliably.

Here is the raw file which will expire in one day.
https://send.firefox.com/download/b2b7725744910dac/#tVCGxdRYD1SW3nTWm6fTzg
Raw files usually have jpeg embedded so that could be used to view image of it does have but when download to other apps it need to give the full raw image. Trying to render raw image is almost impossible. 


If implementing gallery thumbnail view it would also be good to support caching. Most apps allow us to select cache size from 500mb to even go.

**Comment by lithium0003** [comment]
I did try to download the link, but it already expired now. Please make another link.

The thumbnail gallery sounds good but local cache increases risk in encrypted drive. This should be selectable option.

**Comment by prabirshrestha** [comment]
You can download sample NEFs that crashes from here. http://www.luminescentphoto.com/nx2/nefs.html

Option does sound better even better if we can cache it for n days.

**Comment by lithium0003** [comment]
Thanks for send the link, I understand what crashes app. It's a file extension recognition error.
If you have a common RAW image file type extension list or link, please show me. I want to know which file ext should be open by image viewer.
This bug will be fixed next version.

**Comment by prabirshrestha** [comment]
Unfortunately each company has their own format. That is why Adobe created dng so everyone can use it but no manufacture uses that as default. I use nikon so it is always NEF. You can find more here if you want to support other cameras. 

https://en.wikipedia.org/wiki/Raw_image_format#Raw_filename_extensions_and_respective_camera_manufacturers

Most popular ones I would say is Nikon, Cannon, Fuji, Panasonic, Lieca, Gopro, Sony and Adobe dng.

If you want to send testflight builds I'm more then happy to test it out. My email should be in the github profile page.

**Comment by lithium0003** [comment]
In 1.4.0(42), some progress on image viewer. Beta review in progress, please wait it.

**Comment by prabirshrestha** [comment]
Awesome. Looking forward to it. Any plans to push the changes to master branch too? Or are you planning to do this after the release?

**Comment by lithium0003** [comment]
Update master branch now. The Dependency is changed, please re-create in work folder.
