### ISSUE TITLE
Support sorting

### ISSUE THREAD

**Issue by prabirshrestha** [lithium0003/ccViewer#8]
Support sorting by name, file type, size and date.

**Comment by lithium0003** [comment]
Sort in folder will be come in next release. Now beta testing.

**Comment by lithium0003** [comment]
In the internal beta version, implemented it.

**Comment by prabirshrestha** [comment]
Do you have a test flight build that we can try? My email is in my github profile page.

**Comment by lithium0003** [comment]
Sure. Please wait for upload.
